# This is a basic workflow to help you get started with Actions
name: Galaxy Workflows Testing for Push and PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  setup:
    name: Setup cache and test workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Print github context properties
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'sha: ${{ github.sha }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'event.before: ${{ github.event.before }}'
          echo 'event.after: ${{ github.event.after }}'

      - name: Python version installed
        run: python3 --version

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1

      - name: Cache .cache/pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: pip_cache_gxy_testing_workflow

      - name: Install setuptools
        run: pip3 install setuptools

      - name: Install planemo
        run: pip3 install planemo

      - name: Set commit range (push to the main branch, e.g. merge)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "COMMIT_RANGE=${{ github.event.before }}.." >> $GITHUB_ENV

      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE=HEAD~.." >> $GITHUB_ENV

      - name: List of files changed in this commit
        run: |
          git diff $COMMIT_RANGE --color=never --name-only -- '*.ga' '*-test.yml' | sed 's/-test.yml/.ga/' | uniq > files_changed.txt
          find files_changed.txt -size 0 -delete

      - name: Check whether change file is created
        id: files_changed_exists
        uses: andstor/file-existence-action@v1
        with:
          files: "files_changed.txt"

      - name: Run workflows tests on UMSA Galaxy
        if: steps.files_changed_exists.outputs.files_exists == 'true'
        run: |
          while read workflow; do
            workflow_file_name=`basename "$workflow"`
            workflow_file_name_no_ext=`basename -s .ga "$workflow_file_name"`
            planemo test \
            --history_name "$workflow_file_name_no_ext" \
            --galaxy_url ${{ secrets.GALAXY_URL }} \
            --galaxy_user_key ${{ secrets.GALAXY_USER_KEY }} \
            --no_shed_install \
            --engine external_galaxy \
            --test_output "$workflow_file_name_no_ext"_output.html \
            "$workflow"
          done < files_changed.txt

      - name: List repo files
        run: ls -la

      - uses: actions/upload-artifact@v2
        if: steps.files_changed_exists.outputs.files_exists == 'true'
        with:
          name: Workflow testing artifacts
          path: ./*output.html