# This is a basic workflow to help you get started with Actions
name: Galaxy Workflow Testing for push and PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  WORFLOW_TO_TEST: 'LC-MS-pipeline/LC-MS-pipeline.ga'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  setup:
    name: Setup cache and test workflow
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Print github context properties
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'sha: ${{ github.sha }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'event.before: ${{ github.event.before }}'
          echo 'event.after: ${{ github.event.after }}'

      - name: Python version installed
        run: python3 --version

      - uses: actions/checkout@v1

      - name: Cache .cache/pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: pip_cache_gxy_${{ env.WORFLOW_TO_TEST }}

      - name: Install planemo
        run: pip3 install planemo

      - name: Test workflow at UMSA Galaxy
        run: planemo test \
          --history_name "pipeline-testing" \
          --galaxy_url ${{ secrets.GALAXY_URL }} \
          --galaxy_user_key ${{ secrets.GALAXY_USER_KEY }} \
          --no_shed_install \
          --engine external_galaxy \
          ${{ env.WORFLOW_TO_TEST }}

      - uses: actions/upload-artifact@v2
        with:
          name: Workflow testing artifacts
          path: LC-MS-pipeline/tool_test_output.html