name: Weekly workflow testing

on:
  schedule:
    # Run at midnight every monday
    - cron: '0 0 * * 1'

env:
  WORKFLOW_TO_TEST: 'LC_MS_pipeline/LC_MS_pipeline.ga'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  setup:
    name: Setup cache and test workflow
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Print github context properties
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'sha: ${{ github.sha }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'event.before: ${{ github.event.before }}'
          echo 'event.after: ${{ github.event.after }}'

      - name: Python version installed
        run: python3 --version

      - uses: actions/checkout@v1

      - name: Cache .cache/pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: pip_cache_gxy_testing_workflow

      - name: Install planemo
        run: pip3 install planemo

      - name: Test workflow at UMSA Galaxy
        run: |
          for worflow in $(find . -name '*-test.yml' | grep LC_MS | sed 's/-test.yml/.ga/' | sort); do
            workflow_file_name=`basename "$workflow"`
            planemo test \
            --history_name "pipeline-testing" \
            --galaxy_url ${{ secrets.GALAXY_URL }} \
            --galaxy_user_key ${{ secrets.GALAXY_USER_KEY }} \
            --no_shed_install \
            --engine external_galaxy \
            --test_output ./"$workflow_file_name"_output.html \
            "$worflow"
          done

      - name: List repo files
        run: ls -l

      - uses: actions/upload-artifact@v2
        with:
          name: Workflow testing artifacts
          path: ./*output.html