name: Weekly workflow testing

on:
  schedule:
    # Run at midnight every saturday
    - cron: '0 1 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  setup:
    name: Setup cache and test workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: Print github context properties
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'sha: ${{ github.sha }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'event.before: ${{ github.event.before }}'
          echo 'event.after: ${{ github.event.after }}'

      - name: Python version installed
        run: python3 --version

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1

      - name: Cache .cache/pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: pip_cache_gxy_testing_workflow

      - name: Install setuptools
        run: pip3 install setuptools

      - name: Install planemo
        run: pip3 install planemo

      - uses: microsoft/variable-substitution@v1
        with:
          files: 'galaxy-instance.json'
        env:
          galaxy_url: ${{ secrets.GALAXY_URL }}
          user_api_key: ${{ secrets.GALAXY_USER_KEY }}

      - name: Purge user histories in Galaxy
        run: python delete_user_history.py

      - name: Run workflows tests on UMSA Galaxy
        run: |
          for workflow in $(find . -name '*-test.yml' | sed 's/-test.yml/.ga/' | sort); do
            workflow_file_name=`basename "$workflow"`
            workflow_file_name_no_ext=`basename -s .ga "$workflow_file_name"`
            planemo test \
            --history_name "$workflow_file_name_no_ext" \
            --galaxy_url ${{ secrets.GALAXY_URL }} \
            --galaxy_user_key ${{ secrets.GALAXY_USER_KEY }} \
            --no_shed_install \
            --engine external_galaxy \
            --test_output "$workflow_file_name_no_ext"_output.html \
            "$workflow" || continue
          done

      - name: List repo files
        run: ls -l

      - uses: actions/upload-artifact@v2
        with:
          name: Workflow testing artifacts
          path: ./*output.html